name: 巴哈簽到

on:
  schedule:
    - cron: "0 16,20 * * *"
  workflow_dispatch:

jobs:
  automation:
    name: 巴哈簽到自動化
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bahamut Automation
        uses: JacobLinCool/Bahamut-Automation@action
        with:
          modules: "login,ad_handler,sign,guild,answer,lottery,logout,telegram"
          parameters: ${{ secrets.parameters || '{}' }}
          secrets: ${{ secrets.secrets }}
      - uses: gautamkrishnar/keepalive-workflow@master
