name: 巴哈簽到

on:
  schedule:
    - cron: "0 5,13,21 * * *"
  workflow_dispatch:

jobs:
  automation:
    name: 巴哈簽到自動化
    runs-on: macos-10.15
    steps:
      - name: Bahamut Automation
        uses: JacobLinCool/Bahamut-Automation@v0.6.12
        with:
          modules: "login,ad_handler,sign,guild,answer,lottery,logout,telegram"
          parameters: ${{ secrets.parameters }}
